name: backend_server
description: Um backend Dart para um assistente de planos de operadora.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0' # Garante compatibilidade com versões modernas do Dart

dependencies:
  # Framework Web
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: 0.1.5
  
  # API Gemini - Atualizada para a versão estável mais recente
  google_generative_ai: ^0.4.7
  
  # Utilitários
  http: ^1.5.0
  postgres: ^2.6.1
  dotenv: ^4.2.0
  path: ^1.9.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.3
